# Generated by Django 3.2.5 on 2021-09-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirmed',
        ),
    ]
