# Generated by Django 3.2.5 on 2021-09-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_profile_email_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='person',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, help_text='Tell your readers about yourself...', max_length=1000, null=True, verbose_name='About the Writer'),
        ),
    ]
